ALTER TABLE user_account
    ADD COLUMN IF NOT EXISTS role VARCHAR(32) NOT NULL DEFAULT 'USER',
    ADD COLUMN IF NOT EXISTS token_version BIGINT NOT NULL DEFAULT 0;

ALTER TABLE conversation_session
    ADD COLUMN IF NOT EXISTS user_id BIGINT NULL;

ALTER TABLE chat_message
    ADD COLUMN IF NOT EXISTS user_id BIGINT NULL;

ALTER TABLE hot100_problem_progress
    ADD COLUMN IF NOT EXISTS user_id BIGINT NULL;

ALTER TABLE user_refresh_token
    ADD COLUMN IF NOT EXISTS user_id BIGINT NOT NULL,
    ADD COLUMN IF NOT EXISTS token_id VARCHAR(64) NOT NULL,
    ADD COLUMN IF NOT EXISTS token_hash VARCHAR(128) NOT NULL,
    ADD COLUMN IF NOT EXISTS expires_at DATETIME(6) NOT NULL,
    ADD COLUMN IF NOT EXISTS revoked_at DATETIME(6) NULL,
    ADD COLUMN IF NOT EXISTS created_at DATETIME(6) NOT NULL;
